"""updated columns with additional fields

Revision ID: 73b364b14148
Revises: d7df89f97511
Create Date: 2025-02-21 23:49:28.224984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b364b14148'
down_revision: Union[str, None] = 'd7df89f97511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('marks', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'marks', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'marks', 'students', ['student_id'], ['id'])
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'])
    op.add_column('subjects', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'teacher_id')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'group_id')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_column('marks', 'subject_id')
    op.drop_column('marks', 'student_id')
    # ### end Alembic commands ###
